stages:
  generate:
    cmd: recsys-generate
    deps:
      - src/recsys/pipeline/generate.py
      - src/recsys/data/generator_enriched.py
      - src/recsys/data/factory.py
    params:
      - generate
    outs:
      - data/raw/interactions.parquet
  preprocess:
    cmd: recsys-preprocess
    deps:
      - src/recsys/pipeline/preprocess.py
      - src/recsys/preprocessing/splitter.py
      - data/raw/interactions.parquet
    params:
      - preprocess
    outs:
      - data/interim/train.parquet
      - data/interim/test.parquet
  feature_eng:
    cmd: recsys-features
    deps:
      - src/recsys/pipeline/feature_eng.py
      - src/recsys/features/build_features.py
      - data/interim/train.parquet
    outs:
      - data/processed/popularity.parquet
  train:
    cmd: recsys-train
    deps:
      - src/recsys/pipeline/train.py
      - src/recsys/models/baseline.py
      - data/interim/train.parquet
      - data/processed/popularity.parquet
    outs:
      - models/baseline.pkl
  evaluate:
    cmd: recsys-evaluate
    deps:
      - src/recsys/pipeline/evaluate.py
      - src/recsys/evaluation/metrics.py
      - models/baseline.pkl
      - data/interim/test.parquet
    params:
      - evaluate
    metrics:
      - metrics/metrics.json:
          cache: false
  train_svd:
    cmd: recsys-train-svd
    deps:
      - src/recsys/pipeline/train_svd.py
      - src/recsys/models/svd.py
      - src/recsys/preprocessing/encoder.py
      - data/interim/train.parquet
    params:
      - svd
    outs:
      - models/svd.pkl
  evaluate_svd:
    cmd: recsys-evaluate-svd
    deps:
      - src/recsys/pipeline/evaluate_svd.py
      - src/recsys/pipeline/evaluate.py
      - src/recsys/evaluation/metrics.py
      - models/svd.pkl
      - data/interim/test.parquet
    params:
      - evaluate
    metrics:
      - metrics/metrics_svd.json:
          cache: false
  train_embedding:
    cmd: recsys-train-embedding
    deps:
      - src/recsys/pipeline/train_embedding.py
      - src/recsys/models/embedding.py
      - src/recsys/preprocessing/encoder.py
      - data/interim/train.parquet
    params:
      - embedding
    outs:
      - models/embedding.pkl
  evaluate_embedding:
    cmd: recsys-evaluate-embedding
    deps:
      - src/recsys/pipeline/evaluate_embedding.py
      - src/recsys/evaluation/metrics.py
      - models/embedding.pkl
      - data/interim/test.parquet
    params:
      - evaluate
    metrics:
      - metrics/metrics_embedding.json:
          cache: false
